### ISSUE TITLE
Can you share with your hyper parameters?

### ISSUE THREAD

**Issue by XD319328** [bharadwajakshay/targetless_calibration#2]
It's my pleasure to find your project and give me a lot of help about of calibration.But,I can't the file of hyper parameters,for example:
(1)targetless_calibration/data/2011_09_26/2011_09_26_drive_0001_sync/velodyne_points/data/agumenteddata/test_data.json
(2)2011_09_26_drive_0001_sync/velodyne_points/data/agumenteddata/angles_summary.json

**Comment by bharadwajakshay** [comment]
Hey,
This is still a work in progress. 
Check out https://github.com/KleinYuan/RGGNet
or 
https://github.com/epiception/CalibNet
They are more complete.  I will add a tag when this repo ready to be tested.

**Comment by XD319328** [comment]
Thank you for your reply!
&nbsp; &nbsp;I tried to duplicate the calibnet ,but I found some problems are hard to get over.For example:



&nbsp; &nbsp;1、According to calibnet author's advices,I find the "parsed_set.txt" is empty?

&nbsp; &nbsp; &nbsp;( To prepare the dataset, run /dataset_files/dataset_builder_parallel.sh in the directory where you wish to store. We will also create a parser parsed_set.txt for the dataset, that contains the file names for training. )


&nbsp; &nbsp;2、According the paths of code in the project,I can't find the "parameters.json"? only get the ".pth“ model parameters.

&nbsp; &nbsp; ( In author's code::resnet_params_path = "../Extrinsic_Calibration_2/parameters.json" )

&nbsp; &nbsp;And then,I&nbsp;suddenly&nbsp;found&nbsp;that&nbsp;your&nbsp;work&nbsp;is&nbsp;very&nbsp;similar&nbsp;to&nbsp;calibnet,&nbsp;so&nbsp;I&nbsp;look&nbsp;forward&nbsp;to&nbsp;your&nbsp;progress!

&nbsp; &nbsp;Thank you for your reply again! Good luck!

&nbsp; &nbsp;

&nbsp; &nbsp; David

&nbsp; &nbsp;2021-03-28

&nbsp;&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bharadwajakshay/targetless_calibration"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月27日(星期六) 晚上11:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bharadwajakshay/targetless_calibration] Can you share with your hyper parameters? (#2)





 
Hey,
 This is still a work in progress.
 Check out https://github.com/KleinYuan/RGGNet
 or
 https://github.com/epiception/CalibNet
 They are more complete.  I will add a tag when this repo ready to be tested.
